export const site = {
  name: "Omkar Gujja",
  firstName: "Omkar",
  lastName: "Gujja",
  monogram: "OG.",
  title: "AI Engineer",
  location: "Building agentic systems & RAG pipelines",
  email: "omkargujja01@gmail.com",
  linkedin: "https://www.linkedin.com/in/omkar-gujja/",
  github: "https://github.com/omkarg01",
  resume: "/Omkar_Gujja_Resume_AI_Engineer.pdf",
  headline: "I build AI systems that do real work.",
  subhead:
    "Engineering production-minded Generative AI, multi-agent platforms, MCP servers and RAG pipelines, from prototype to tools people actually use.",
  tags: [
    "Generative AI",
    "Agentic AI",
    "RAG",
    "MCP",
    "LLM Systems",
    "Production AI",
  ],
  about:
    "I design and ship agentic AI systems, from MCP-powered HR assistants to multi-agent coordinators and domain RAG pipelines. My focus is turning frontier models into reliable tools: clear routing, grounded retrieval, and interfaces people actually use.",
  skills: [
    "LangChain",
    "Model Context Protocol",
    "RAG & Vector Search",
    "Agno Multi-Agent",
    "Semantic Routing",
    "Groq · LLMs",
    "ChromaDB · FAISS",
    "FastAPI · Streamlit",
    "Python",
    "PostgreSQL",
    "Docker",
  ],
};

export const manifesto = [
  {
    number: "01",
    title: "Production first, demo never",
    body: "Every system I build starts with a constraint: token cost, retrieval accuracy, or response latency, and works backward to an architecture that holds up under real users and real data. If it can't survive production, it doesn't ship.",
  },
  {
    number: "02",
    title: "Agents with boundaries",
    body: "I build multi-agent systems where each agent has a defined role, explicit tool access, and clear handoff logic. Autonomy comes from structure, not from hoping a single prompt handles everything. Coordinator patterns, not chaos.",
  },
  {
    number: "03",
    title: "Retrieval that's actually grounded",
    body: "RAG pipelines only work when the context is right. I build retrieval layers with semantic chunking, vector search, and source-aware filtering, so the model answers from your data, not its imagination. Built this for live company data at Exponentia.ai.",
  },
  {
    number: "04",
    title: "AI embedded in the product, not bolted on",
    body: "LLM integration means the AI layer touches the frontend, the API, and the data pipeline. I own all three, from the Angular or React interface down to the FastAPI service and the retrieval backend. One engineer, full ownership.",
  },
  {
    number: "05",
    title: "Evals before celebration",
    body: "Before anything goes to a client, I test it against the metric it was built for. Response quality, cost per query, latency under load. Shipping without evals is guessing. I'd rather know.",
  },
];

export const stats = [
  {
    value: 4,
    suffix: "+",
    label: "Years of Experience",
    detail: "Shipping web apps and AI systems across freelance and product work",
  },
  {
    value: 8,
    suffix: "+",
    label: "Systems Built",
    detail: "RAG agents, MCP tools, multi-agent apps, and full-stack platforms",
  },
  {
    value: 100,
    suffix: "+",
    label: "GitHub Repositories",
    detail: "Active builder with public work across frontend, backend, and AI",
  },
  {
    value: 15,
    suffix: "+",
    label: "Tools & Frameworks",
    detail: "FastAPI, Databricks, MCP, LangChain, React, Node, and more",
  },
];

export const projects = [
  {
    id: "01",
    title: "Exponentia Agent",
    subtitle: "RAG · Databricks",
    category: "Enterprise AI",
    featured: true,
    description:
      "AI knowledge chatbot for Exponentia.ai that answers website and docs questions with RAG, cites sources, suggests follow-ups, and escalates unanswered queries by email. FastAPI backend designed to embed in Webflow.",
    outcome: "Grounded answers with citations, sessions & email escalation",
    highlights: [
      "Databricks Vector Search",
      "Source citations",
      "Follow-up suggestions",
      "Webflow embed",
    ],
    flow: ["Query", "Vector Search", "LLM", "Cite + Escalate"],
    stack: [
      "FastAPI",
      "Databricks",
      "Claude",
      "Groq",
      "SMTP",
      "Webflow",
    ],
    preview: "exponentia" as const,
    mock: {
      query: "What services does Exponentia offer for generative AI?",
      answer:
        "Exponentia helps enterprises design and ship GenAI solutions, from strategy to production systems grounded in your data.",
      sources: ["docs/services.md", "website/genai"],
      followUps: [
        "How does the RAG pipeline work?",
        "Can this embed on our site?",
      ],
      escalated: false,
    },
    href: "https://www.exponentia.ai/",
    linkLabel: "Company site",
    github: "",
  },
  {
    id: "02",
    title: "Multi-Agent Commerce Desk",
    subtitle: "Agno + Groq",
    category: "Multi-Agent",
    featured: true,
    description:
      "Four-agent commerce system: a coordinator plans the run, FAQ (web search) and Inventory specialists answer in parallel, a reviewer checks their drafts, then the coordinator composes one answer for stock, pricing, and product questions.",
    outcome: "One query → specialists + review → one answer",
    highlights: ["4 agents", "Parallel specialists", "Reviewer loop"],
    flow: ["User", "Coordinator", "Specialists", "Reviewer"],
    stack: ["Agno", "Groq", "Streamlit", "DuckDuckGo"],
    preview: "agents" as const,
    mock: {
      query:
        "Do you have wireless headphones in stock, and what's the return policy?",
      agents: [
        { name: "Coordinator", role: "Planning…", active: true },
        { name: "Inventory", role: "Stock + price", active: true },
        { name: "FAQ", role: "Policy search", active: true },
      ],
      answer: "Yes: 24 units in Audio. Returns accepted within 30 days.",
    },
    href: "https://multi-agent-commerce-desk.streamlit.app/",
    github: "https://github.com/omkarg01/multi-agent-commerce-desk",
  },
  {
    id: "03",
    title: "HR Assist",
    subtitle: "MCP Server",
    category: "Agentic Tools",
    featured: true,
    description:
      "Agentic HR assistant exposing employee, leave, meeting, ticket, and email tools over the Model Context Protocol, built for onboarding automation with Claude Desktop and other MCP clients.",
    outcome: "Onboarding flows as tool calls, not chat scripts",
    highlights: ["5+ MCP tools", "Onboarding prompt", "Gmail hooks"],
    flow: ["MCP Client", "Tool Router", "HR APIs", "Email"],
    stack: ["MCP", "Python", "uv", "Gmail API"],
    preview: "mcp" as const,
    mock: {
      tools: [
        { name: "add_employee", status: "ready" },
        { name: "apply_leave", status: "ready" },
        { name: "schedule_meeting", status: "ready" },
        { name: "create_ticket", status: "ready" },
        { name: "send_welcome_email", status: "active" },
      ],
      prompt: "onboard_new_employee → Riya Shah",
    },
    href: "https://hr-assist-mcp-server.streamlit.app/",
    github: "https://github.com/omkarg01/HR-Assist-MCP-Server",
  },
  {
    id: "04",
    title: "ProShop",
    subtitle: "MERN + Tambo AI",
    category: "Full Stack · Generative UI",
    featured: false,
    description:
      "Full-featured MERN eCommerce platform (cart, checkout, PayPal, admin) extended with Tambo AI. The assistant returns interactive UI components in chat, not just text: product cards, sales dashboards, inventory tools, and order history.",
    outcome: "Chat replies as live components, not paragraphs",
    highlights: [
      "Generative UI",
      "SmartProductCard",
      "Sales & Admin dashboards",
      "PayPal checkout",
    ],
    flow: ["User prompt", "Tambo AI", "UI Component", "Live store"],
    stack: ["MongoDB", "Express", "React", "Node", "Redux", "Tambo AI"],
    preview: "tambo" as const,
    mock: {
      prompt: "Show me details and reviews for the iPhone 15 Pro.",
      component: "SmartProductCard",
      components: [
        "SmartProductCard",
        "AdminDashboard",
        "SalesDashboard",
        "OrderHistoryCard",
      ],
    },
    href: "https://proshop-6ko3.onrender.com/",
    github: "https://github.com/omkarg01/Proshop",
  },
  {
    id: "05",
    title: "E-commerce RAG",
    subtitle: "Semantic Router",
    category: "RAG Pipeline",
    featured: false,
    description:
      "Customer chatbot that classifies intent with semantic routing, then answers via FAQ retrieval (ChromaDB), product SQL search, or small-talk, powered by Groq.",
    outcome: "Intent-aware answers across FAQ, SQL & chat",
    highlights: ["3 routes", "ChromaDB", "SQL products"],
    flow: ["Query", "Router", "Chroma / SQL", "Groq"],
    stack: ["RAG", "ChromaDB", "Semantic Router", "Groq"],
    preview: "rag" as const,
    mock: {
      query: "Show me running shoes under $100",
      route: "SQL · Product Search",
      confidence: "0.91",
      hits: ["Nike Pegasus ($89)", "Adidas Runfalcon ($72)", "FAQ skipped"],
    },
    href: "https://e-commerce-chatbot-tool.streamlit.app/",
    github: "https://github.com/omkarg01/E-commerce-chatbot-tool",
  },
  {
    id: "06",
    title: "Real Estate RAG",
    subtitle: "Research Tool",
    category: "Retrieval",
    featured: false,
    description:
      "URL-driven research assistant that loads articles, embeds them with HuggingFace models, and answers questions with grounded sources via LangChain + ChromaDB.",
    outcome: "Source-cited answers from live article URLs",
    highlights: ["URL ingest", "Citations", "Llama 3"],
    flow: ["URLs", "Embed", "ChromaDB", "Llama 3"],
    stack: ["LangChain", "ChromaDB", "Groq", "Streamlit"],
    preview: "research" as const,
    mock: {
      urls: [
        "housingwire.com/markets-q2…",
        "realtor.com/trends-2024…",
        "nar.realtor/research…",
      ],
      question: "What drove inventory changes this quarter?",
      citation: "Source 2 · para 4",
    },
    href: "https://real-estate-research-tool-og.streamlit.app/",
    github: "https://github.com/omkarg01/Real-Estate-Research-Tool",
  },
  {
    id: "07",
    title: "Memory Intelligence System",
    subtitle: "In progress",
    category: "Long-term Memory",
    featured: false,
    description:
      "A memory layer for AI agents that stores, retrieves, and ranks long-term context across sessions, so assistants remember users, preferences, and prior decisions without stuffing everything into the prompt.",
    outcome: "Persistent agent memory beyond a single chat window",
    highlights: ["Memory store", "Retrieval ranking", "Session continuity"],
    flow: ["Events", "Memory store", "Retrieve", "Inject context"],
    stack: ["Python", "Vector DB", "LLMs", "FastAPI"],
    preview: "soon" as const,
    mock: {
      status: "In progress",
      progress: 45,
      focus: "Long-term memory graph & retrieval APIs",
    },
    href: "",
    github: "",
  },
  {
    id: "08",
    title: "AI PR Review Agent",
    subtitle: "In progress",
    category: "Developer Tools",
    featured: false,
    description:
      "An agent that reviews pull requests with repo context: diffs, conventions, and risk signals. Aimed at faster, more consistent code review without replacing human judgment.",
    outcome: "Automated PR feedback grounded in your codebase",
    highlights: ["Diff analysis", "Repo context", "Review comments"],
    flow: ["PR event", "Context pack", "Review agent", "Comments"],
    stack: ["GitHub API", "LLMs", "Python", "CI"],
    preview: "soon" as const,
    mock: {
      status: "In progress",
      progress: 30,
      focus: "Diff ingestion & review rubric",
    },
    href: "",
    github: "",
  },
];

export const featuredProjects = projects.filter((p) => p.featured);
